### ISSUE TITLE
Move Ledger signer plugin to this repository

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-core-ledger#13]
Once oasis-core gets a plugin-based signer (see oasisprotocol/oasis-core#3120), we should transfer the Ledger signer to this repository.

Some required steps after the transfer include:
* Set up CI to test against versions of Oasis Core.
* Probably also move all of the existing support code to an `internal` package.
* Basic CLI for operations like "list ledger devices".

**Comment by Yawning** [comment]
Done by #16.

**Comment by tjanez** [comment]
> Set up CI to test against versions of Oasis Core.

Filled separate issue for that: #22.
