### ISSUE TITLE
Add a CLI command that shows the staking account address on a device

### ISSUE THREAD

**Issue by tjanez** [oasisprotocol/oasis-core-ledger#53]
Add a CLI command, e.g. `show_address`, that would show the staking account address for a chosen wallet and its account index (0-based) specified via the `--wallet_id` and `--index` flags.

For example, running:
```
oasis-core-ledger show_address --wallet_id 431fc6 --index 0
```

would output:
```
Ensure that the staking account address that is shown on the chosen Ledger device's screen is:
oasis1qpvepen4zpymf4te30s7lchftgr3egjs5qd9egyu
```
and show the staking account address for the chosen Ledger device with the account index of 0 on the Ledger's screen.

**Comment by kostko** [comment]
It would be great if it would also show the address in the CLI ;-) Also there probably needs to be an argument for specifying the wallet ID?

**Comment by tjanez** [comment]
> It would be great if it would also show the address in the CLI ;-)

Yes, of course :slightly_smiling_face: .

> Also there probably needs to be an argument for specifying the wallet ID?

Indeed.

I've added both to the description.
